import Head from 'next/head'
import styled from 'styles/Home.module.css'
import { Slider } from 'components/Home/Slider'

export default function Home() {
	return (
		<div className={styled.container}>
			<Head>
				<title>Home - Logística y Transporte Atalaya S.A.S</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.png' />
			</Head>
			<Slider />
			<h2>
				Ofrecemos soluciones especializadas
				<br />y adaptadas a las necesidades de los clientes
			</h2>
			<div className={styled.CardContainer}></div>
		</div>
	)
}
